name: dockerCI

on:
  push:
    branches:
      - "main"
    paths-ignore:
      - '**.md'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
          name: Build and push
          uses: docker/build-push-action@v4
          with:
            context: .
            file: ./StudentCI/Dockerfile
            push: true
            tags: ${{ secrets.DOCKERHUB_USERNAME }}/clockbox:latest
      - name: Test
        run: dotnet test ./tests/StudentCI.Tests.csproj
